apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-pod
    #image: gopikrishna99899/project2:9
    image: nginx
    ports:
      - containerPort: 80
---
